# Autograd with tensors

In [22]:
import torch

In [23]:
w = torch.randn(4,3, requires_grad=True)

In [24]:
w 

tensor([[ 1.3115,  0.3301,  1.4035],
        [ 0.1786,  0.7160, -0.1066],
        [-0.8963, -1.4334,  0.2955],
        [ 0.1453,  0.5659, -0.6640]], requires_grad=True)

In [25]:
w.requires_grad_(False)

tensor([[ 1.3115,  0.3301,  1.4035],
        [ 0.1786,  0.7160, -0.1066],
        [-0.8963, -1.4334,  0.2955],
        [ 0.1453,  0.5659, -0.6640]])

In [26]:
w.requires_grad_(True)

tensor([[ 1.3115,  0.3301,  1.4035],
        [ 0.1786,  0.7160, -0.1066],
        [-0.8963, -1.4334,  0.2955],
        [ 0.1453,  0.5659, -0.6640]], requires_grad=True)

In [27]:
y = torch.exp(w)

In [28]:
y

tensor([[3.7119, 1.3911, 4.0695],
        [1.1956, 2.0462, 0.8989],
        [0.4081, 0.2385, 1.3438],
        [1.1564, 1.7609, 0.5148]], grad_fn=<ExpBackward>)

In [29]:
print(y.grad_fn)

In [30]:
outp = y.mean()
print(outp)

tensor(1.5613, grad_fn=<MeanBackward0>)


In [31]:
print(w.grad)

None


In [32]:
outp.backward() # calculation of the gradient

In [33]:
print(w.grad) # print the calculated grads

tensor([[0.3093, 0.1159, 0.3391],
        [0.0996, 0.1705, 0.0749],
        [0.0340, 0.0199, 0.1120],
        [0.0964, 0.1467, 0.0429]])


In [34]:
print(w.detach()) # will prevent update of the gradient in the future

tensor([[ 1.3115,  0.3301,  1.4035],
        [ 0.1786,  0.7160, -0.1066],
        [-0.8963, -1.4334,  0.2955],
        [ 0.1453,  0.5659, -0.6640]])


In [35]:
print(w.grad)

tensor([[0.3093, 0.1159, 0.3391],
        [0.0996, 0.1705, 0.0749],
        [0.0340, 0.0199, 0.1120],
        [0.0964, 0.1467, 0.0429]])


In [37]:
with torch.no_grad(): # prevention of tracking history
    outp = (w+y).mean() 
    
print(outp.requires_grad)

False
