In [1]:
import numpy as np

In [3]:
# random number between 0 and one- the number of numbers generated is the argument
np.random.rand(1)

array([0.28297878])

In [4]:
np.random.rand(3)

array([0.02742692, 0.8152713 , 0.7688551 ])

In [5]:
np.random.rand(5,6)

array([[0.1921971 , 0.18696729, 0.46317547, 0.73288632, 0.23971799,
        0.98337287],
       [0.31984479, 0.99482491, 0.16018479, 0.58716814, 0.67414448,
        0.39739276],
       [0.74508027, 0.63536438, 0.30676797, 0.74981945, 0.82041182,
        0.25211922],
       [0.78384427, 0.1811471 , 0.39652778, 0.8188987 , 0.06310398,
        0.29136543],
       [0.75567522, 0.66514108, 0.29535474, 0.35832236, 0.86611093,
        0.19743492]])

In [6]:
# random number from the standart normal distribution
np.random.randn(6)

array([-0.15588007, -0.2485909 , -0.50247368,  0.29996981,  2.25756633,
        0.19907543])

In [8]:
# generate #third argument# integer numbers between "first and second argument" values
np.random.randint(1,9000,5)

array([2638, 6428, 5506, 1640, 3838])

In [12]:
# to "lock" the random numbers genrated for a specific cell-
np.random.seed(9000)
np.random.rand(4)

array([0.29222481, 0.98730699, 0.8791066 , 0.39042672])

In [13]:
arr = np.arange(9)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
ranarr = np.random.randint(0,20,10)
ranarr

array([11, 17,  2,  2, 11,  3,  7, 13, 18,  5])

In [17]:
#reshaping the length 9 arr
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# getting max/min value in the array
ranarr.max()

18

In [19]:
# getting the index location of the max/min input of the array
ranarr.argmax()

8

In [20]:
#type of he inputs of the array
ranarr.dtype

dtype('int32')