In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# inexing and selection
arr[9]

9

In [4]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [11]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [18]:
# slicing
sliceOfArray = arr[0:6]

In [19]:
sliceOfArray

array([99, 99, 99, 99, 99, 99])

In [20]:
sliceOfArray[:] = 99

In [21]:
sliceOfArray

array([99, 99, 99, 99, 99, 99])

In [22]:
# because te broadcasting still looking at the original array, any change of the new array will affect the original
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
# to make changes that will not affect the original array
arr_copy = arr.copy()

In [27]:
arr[:] = 50

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [40]:
#Indexing on 2d array

In [41]:
arr_2d = np.random.randint(0,20,9)

In [43]:
arr_2d = arr_2d.reshape(3,3)

In [45]:
# to ge row at "first bracets argument position"
arr_2d[1]

array([11, 16, 10])

In [48]:
# getting a specific item
arr_d[1][2]

10

In [49]:
arr_2d[1,2]

10

In [51]:
arr_2d

array([[ 8, 19, 13],
       [11, 16, 10],
       [ 6,  5,  1]])

In [52]:
# get part of the 2d array
arr_2d[:2,1:]

array([[19, 13],
       [16, 10]])

In [53]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
# using a boolean arry to get values where the bool array is set to True
bool_arr = arr > 4

In [56]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
#can do the same in one step
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])