# Tensors 

In [1]:
import torch

## zeros()

In [4]:
w = torch.zeros(3,4)

In [5]:
w

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## size() and shape

In [6]:
w.size()

torch.Size([3, 4])

In [7]:
w.shape

torch.Size([3, 4])

## randn() and randn_like()

In [8]:
w = torch.randn(3,4)

In [9]:
w

tensor([[-0.2126,  0.2917,  0.7332, -0.7636],
        [ 0.3857, -0.5238, -0.9079, -0.0463],
        [ 0.1235, -0.7485,  0.1723,  0.7458]])

In [10]:
t = torch.randn_like(w)

In [11]:
t

tensor([[ 0.6293, -0.8739,  0.0788, -0.3029],
        [-0.6054,  1.0637, -0.4412,  0.7506],
        [-2.1822, -0.1516, -1.6919,  1.8463]])

## fill_()

In [12]:
t.fill_(2)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

## view()

In [13]:
w.view(6,2)

tensor([[-0.2126,  0.2917],
        [ 0.7332, -0.7636],
        [ 0.3857, -0.5238],
        [-0.9079, -0.0463],
        [ 0.1235, -0.7485],
        [ 0.1723,  0.7458]])

In [14]:
t.view(-1,6)

tensor([[2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.]])

## numpy()