In [2]:
import numpy as np

In [3]:
import cv2

In [4]:
img = cv2.imread('Exercise Files/images/typewriter.jpg')
rows = open('Exercise Files/model/synset_words.txt').read().strip().split("\n")

In [5]:
classes = [r[r.find(' ')+ 1:]for r in rows]

In [17]:
net = cv2.dnn.readNetFromCaffe('Exercise Files/model/bvlc_googlenet.prototxt', 'Exercise Files/model/bvlc_googlenet.caffemodel') # importing the model
blob = cv2.dnn.blobFromImage(img, 1, (224,224)) # rescaling image size to the model requirements
net.setInput(blob) # set the blob as input layer of the net
outp = net.forward() # inference
#print(outp)

In [18]:
idx = np.argsort(outp[0])[::-1][:5] # sorting in descending order and show the top 5 

for (i,id) in enumerate(idx):
    print('{}. {} ({}): Propability {:.3}%'.format(i+1, classes[id], id, outp[0][id]*100)) # show propability with 3 significant digits

1. typewriter keyboard (878): Propability 85.2%
2. space bar (810): Propability 5.53%
3. radiator (753): Propability 2.05%
4. switch, electric switch, electrical switch (844): Propability 0.905%
5. stove (827): Propability 0.863%


In [8]:
# for (i,c) in enumerate(classes):
#     if i==4:
#         break
#     print(i,c)

0 tench, Tinca tinca
1 goldfish, Carassius auratus
2 great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias
3 tiger shark, Galeocerdo cuvieri


In [9]:
print(img.shape)

(971, 1428, 3)


In [10]:
b = img[:,:,0]
print(b)

[[  6   6   6 ...   6   6   6]
 [  6   6   6 ...   6   6   6]
 [  6   6   6 ...   6   6   6]
 ...
 [  0   0   0 ...   0   0   0]
 [209 209 209 ... 209 209 209]
 [255 255 255 ... 255 255 255]]


In [11]:
g = img[:,:,1]
r = img[:,:,2]


In [12]:
cv2.imshow('Image', img) #plot image
cv2.imshow('Blue', b) #plot image -Blue Channel
cv2.imshow('Green', g) #plot image-Green Channel
cv2.imshow('Red', r) #plot image-Red Channel

In [13]:
cv2.waitKey(300000000) # execution is paused until a key is pressed 
cv2.destroyAllWindows() # close image window when a key i pressed